### ISSUE TITLE
Root node initialization and problems with MCST

### ISSUE THREAD

**Issue by viktortuul** [YoshuaNava/DD2380_Project#3]
The root node should be initialized in `game.py` inside the method `new_piece`, as this method is called when a new brick is spawned. Currently, the root node is initialized in `core.py` (even before the game is started, which implies that the root is "Null").

There are some issues in the MCST class. If a node has no children, the commands
`random.choice(node.children) `
and
`random.choice(unexplored_children)`
returns an index error.

**Comment by YoshuaNava** [comment]
Hey, just fixed this. The problem was that we were calling the function getChildren from GameNode a lot of times. But after he activated the hashtable, it was returning an empty list of Children.

The solution was to save the node children the first time you run the function. and from that point just return it when the user calls the functions.

Also, to prevent confusions, we changed the name from getChildren to getFutureStates.
